version: 1.0.0.{build}

image: Visual Studio 2017

configuration: Release

init:
- ps: dotnet --info

environment:
  VersionSuffix: CI.{version}

before_build:
- ps: dotnet restore -v Minimal

build:
  verbosity: minimal

artifacts:
- path: '**\*.nupkg'
