version: 1.0.0.{build}

image: Visual Studio 2017

configuration: Release

init:
- ps: $Env:VersionSuffix = "CI." + $Env:APPVEYOR_BUILD_NUMBER
- ps: dotnet --info

before_build:
- ps: dotnet restore -v Minimal

build:
- ps: dotnet build -c Release --version-suffix $Env:VersionSuffix

artifacts:
- path: '**\*.nupkg'
